### ISSUE TITLE
Elasticsearch 8.0 - Exception: Action/metadata line [1] contains an unknown parameter [_type]

### ISSUE THREAD

**Issue by pankof** [serilog-contrib/serilog-sinks-elasticsearch#409]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] net 5.0
- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

I am getting this error when serilog tries to log to elasticsearch version 8.0. 

 ` Exception: Action/metadata line [1] contains an unknown parameter [_type]`

According to the documentation, Elasticsearch 8.0 no longer supports mapping types.

**Comment by jnus** [comment]
@pankof  - did you get this issue resolved. Running into the same problem

**Comment by pankof** [comment]
No, I just saw it was already open and closed it. Sorry for this.
