### ISSUE TITLE
Bug: IndexAliases does not assign aliases on index creation

### ISSUE THREAD

**Issue by driml** [serilog-contrib/serilog-sinks-elasticsearch#448]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
8.4.1

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**
- [X] 4.6.x

**Please describe the current behavior?**
Setting IndexAliases does nothing -> the created index in elasticsearch does not have any aliases assigned (in settings the rollover_aliases and name in "lifecycle" are empty) and trying to assign a lifetime policy with rollover behavior will also throw an error that aliases are missing.

**Please describe the expected behavior?**
Aliases should be working

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
`var logLevelSwitch = new LoggingLevelSwitch();
	logLevelSwitch.MinimumLevel = (LogEventLevel)elasticSearchMinimumLogLevel;
	
	ElasticLogger = new LoggerConfiguration().MinimumLevel.ControlledBy(logLevelSwitch)
		.WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri(elasticSearchUrl))
		{
			AutoRegisterTemplate = true,
			AutoRegisterTemplateVersion = AutoRegisterTemplateVersion.ESv7,
			OverwriteTemplate = true,
			DetectElasticsearchVersion = false,
			IndexFormat = "testIndex-{0:yyyy.MM.dd}",
			IndexAliases = new[] {"testIndex"},
			CustomFormatter =  new ElasticsearchJsonFormatter(false, null, true,
				null, null, false, false, false),
			Period = TimeSpan.FromSeconds(2),
			BatchPostingLimit = 50,
			ModifyConnectionSettings = x => x.BasicAuthentication(username, password),
			EmitEventFailure = EmitEventFailureHandling.WriteToSelfLog,
		})
		.CreateLogger();
}`

**Comment by AlexGoris-KasparSolutions** [comment]
@driml Did you find a solution to this? I still seem to be having the same issue in 8.4.1

**Comment by driml** [comment]
No, never found a solution.

**Comment by hmendozaDBA** [comment]
So Aliases are not working, how could I open this issue? or should a new one be created?
