### ISSUE TITLE
No way how to find out that logging failed

### ISSUE THREAD

**Issue by PatrikBak** [serilog-contrib/serilog-sinks-elasticsearch#457]
This will do nothing when I'm not running Elastic. It should throw.

```csharp
var loggerConfig = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://localhost:123"))
    {
        EmitEventFailure = EmitEventFailureHandling.ThrowException
    });

var logger = loggerConfig.CreateLogger();
logger.Information("Test {value}", 42);
```

Version: .NET 6.0, Serilog 2.11.0, Serilog.Sinks.Elasticsearch 8.4.1

**Comment by chrismacklin** [comment]
I ran into this as well, the issue is that the exception is ultimately caught and logged by Serilog itself, which will do nothing if the self log isn't configured. This should fit it:
```C#
Serilog.Debugging.SelfLog.Enable(msg => Console.WriteLine(msg));
```

**Comment by AlexGoris-KasparSolutions** [comment]
> I ran into this as well, the issue is that the exception is ultimately caught and logged by Serilog itself, which will do nothing if the self log isn't configured. This should fit it:
> 
> ```cs
> Serilog.Debugging.SelfLog.Enable(msg => Console.WriteLine(msg));
> ```

This helped me, issue should be closed
