### ISSUE TITLE
Bug: Using 'message' as propertyname drops the log entry

### ISSUE THREAD

**Issue by user114145** [serilog-contrib/serilog-sinks-elasticsearch#483]
**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
8.4.1

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**
Windows, .NET 6

**Please describe the current behavior?**
When using a messageformat in the` ILogger.<Loglevel>(messageTemplate, propertyValue) `family of functions, using '_message_' as propertyname as depicted below will result in the logmessage (quietly) not being processed.
The behavior cannot be reproduced by using serilog with a different sink.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
![image](https://user-images.githubusercontent.com/9717480/205298356-c1df9626-f1cb-42f2-997e-a44ed2a76b28.png)
![image](https://user-images.githubusercontent.com/9717480/205298531-f01a1eca-1466-4721-a004-5779536ca9a3.png)

**Comment by ricardodemauro** [comment]
The field "message" is used as special field in elastic search. If you really need to keep "message" you should change in the configuration file the property "inlineFields": false

this will produce a second level of fields

**Comment by user114145** [comment]
Right. Sounds sensible.
Nasty to pin down though.
