### ISSUE TITLE
Cannot connect to OpenSearch after update to 9.0.0-rc1: `The client noticed that the server is not Elasticsearch and we do not support this unknown product.`

### ISSUE THREAD

**Issue by KrzysFR** [serilog-contrib/serilog-sinks-elasticsearch#508]
After upgrading from package **9.0.0-beta7** to **9.0.0-rc1**, I am not able to connect to a remote OpenSearch 2.3 instance any more.

Using 9.0.0-beta7, the logs were sent correctly. After upgrading to 9.0.0-rc1, we see multiple `UnsupportedProductException` errors with message `The client noticed that the server is not Elasticsearch and we do not support this unknown product.` coming from inside the `Elasticsearch.Net` package.

I tried changing multiple options with no changes, the current options I set are:
```c#
...
sinkOptions.AutoRegisterTemplate = true;
sinkOptions.AutoRegisterTemplateVersion = AutoRegisterTemplateVersion.ESv7;
sinkOptions.TypeName = null;
````

Rolling back to 9.0.0-beta7 "fixes" the issue.

Looking at the code in the ElasticSearch client, it throws the exception when it get a `ProductCheckStatus.InvalidProduct` from the "product check" logic:
![image](https://user-images.githubusercontent.com/1662235/215842606-08dd63d6-1224-483d-aad3-353ae567289e.png)

It seems to be testing if the server product name contains "Elasticsearch" explicitly:
![image](https://user-images.githubusercontent.com/1662235/215842547-54e06342-7662-43a5-ac10-ac8b4942ebe3.png)

_Sorry I only have a screenshot for this part of the code when trying to diagnose with a debugger attached_

I'm not sure what would explain this regression: it seems that this version of ElasticSearch.Net can never be compatible with something other than ElasticSearch itself. But serilog-sinks-elasticsarch used to work fine with OpenSearch until the recent updates?

Is this change expected or is it an unexpected regression due to adding support for ES8 ? If support for OpenSearch is dropped it would be a potentially big issue for us.

Edit:

Setting `DetectElasticsearchVersion` to `true` or `false` does not change the behavior.

**Comment by nenadvicentic** [comment]
That is the message coming from `Elasticseach.NET` client version 7.16+. It explicitly checks that the product is `Elasticserach` and major version between 6 and 8, before it allows any client request to be executed.

**Comment by KrzysFR** [comment]
Yes that is what I observed, but this did not happen with previous version of the serilog-sinks-elasticsearch package. What can I do to workaround this issue? If v9 of this package is no longer compatible with OpenSearch this will break everyone who was using v8 when upgrading?

**Comment by KrzysFR** [comment]
I found this comment here https://github.com/elastic/elasticsearch-net/issues/5950#issuecomment-902658200 that explicitly confirm that the v7.14+ of ESNET are not compatible anymore with OpenSearch and equivalent.

Does this mean that this Serilog sink is no longer compatible as well, unless support is added explicitly for OpenSearch, using the OpenSearch .NET library (https://github.com/opensearch-project/opensearch-net) ?

**Comment by mivano** [comment]
Hmm, I was not aware of Opensearch and the Elasticsearch story, so sorry if this is breaking at the moment. 

But in essence; this sink is for Elasticsearch and uses their client libraries, which we did upgrade and will keep updating for sure. There is also no test case against open search. 

So either stick with an older version, or use an alternative implementation to access open search would be my suggestion.

**Comment by SaarFroind** [comment]
I ran into the same issue - since this is the only Serilog sink that (intentionally or unintentionally) supported Opensearch -
I would suggest adding a note about this in the Breaking Changes section of Version 9 (Updated Elasticsearch packages no longer support server versions < ESv7 and that includes Opensearch)

**Comment by mivano** [comment]
That is indeed good to mention. Thanks for the PR!

**Comment by polferov** [comment]
We also ran into this issue, so we created a nuget package that implements the Serilog's ILogEventSink: https://github.com/appfacterp/AppFact.SerilogOpenSearchSink
